### ISSUE TITLE
Play Session notes menu doesn't open

### ISSUE THREAD

**Issue by MysteriousAeon** [wagenknecht/Backloggd-Android-App#1]
Normally when you mark something on your Journal, you can click the pink "Played" button again to open a window where you can write down notes, to detail that play session. This function is broken in the app.

https://github.com/user-attachments/assets/5f9b5dba-0630-46ff-a229-61011a7b17bb

**Comment by wagenknecht** [comment]
Hey man, thanks for reporting, seems to be a problem with the second popup on top of the first one. I could recreate the bug and will look into it.

**Comment by wagenknecht** [comment]
New Release 1.1 fixed
